//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace notifications_transport_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public string docNumber { get; set; }
        public System.DateTime docDate { get; set; }
        public string codeIESBK { get; set; }
        public string codeOKE { get; set; }
        public string emailClient { get; set; }
        public string phoneClient { get; set; }
        public System.DateTime checkDate { get; set; }
        public string checkTime { get; set; }
        public string addressEPU { get; set; }
        public string filial { get; set; }
        public string emailFilial { get; set; }
        public string phoneFilial { get; set; }
        public string sendStatus { get; set; }
        public Nullable<System.DateTime> sendDateFact { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> sendDatePlan { get; set; }
        public System.DateTime dateAdded { get; set; }
        public string clientType { get; set; }
    }
}
